on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ftp.a2farmmilk.com
        FTP_USERNAME: agrisoft
        FTP_PASSWORD: agrisoft
        ARGS: --delete
        # --delete arg will delete files on the server if you've deleted them in git
